---
- name: Install php-fpm & php extensions
  become: true
  ansible.builtin.apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - php-fpm
    - php-gd
    - php-curl
    - php-mysql
    - php-dom
    - php-xml

- name: Configure php-fom with apache2
  become: true
  ansible.builtin.copy: src=files/www.conf dest=/etc/php/7.0/fpm/pool.d/
- name: Restart php-fpm
  become: true
  ansible.builtin.service: name=php7.0-fpm state=restarted
