---
- name: Install apache2 web server
  become: true
  ansible.builtin.apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - apache2
    - libapache2-mod-fastcgi

- name: Enable apache2 modules
  become: true
  ansible.builtin.command: a2enmod rewrite actions alias fastcgi proxy_fcgi
- name: Upload apache2 default configuration
  become: true
  ansible.builtin.copy: src=files/000-default.conf dest=/etc/apache2/sites-enabled/
- name: Remove default apache2 index.html file
  become: true
  ignore_errors: true
  ansible.builtin.command: rm /var/www/html/index.html
- name: Upload default index.php for host
  become: true
  ansible.builtin.copy: src=files/index.php dest=/var/www/html/ mode=0644
- name: Restart webserver
  become: true
  ansible.builtin.service: name=apache2 state=restarted
